springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: ENC(p5QyHk3SC4sLcHj94sGTltNxS8kobYkS7Es3zy2oMsU=)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

spring:
  datasource:
    url: ENC(hswedMZ4hDe4DKTFoGF0a0uXXoxmZeIlqTkjoh/wN4ypV/vhgCW6cRjKMebiT7r6)
    username: myuser
    password: ENC(fx879Zcsxn8PaF27WkSlew==)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

