server:
  port: 80

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(hswedMZ4hDe4DKTFoGF0a0uXXoxmZeIlqTkjoh/wN4ypV/vhgCW6cRjKMebiT7r6)
    username: myuser
    password: ENC(fx879Zcsxn8PaF27WkSlew==)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: false
